-- AlterTable
ALTER TABLE "Imagen" ADD COLUMN     "group" INTEGER DEFAULT 0,
ADD COLUMN     "height" INTEGER DEFAULT 128,
ADD COLUMN     "width" INTEGER DEFAULT 128,
ADD COLUMN     "x" INTEGER DEFAULT 0,
ADD COLUMN     "y" INTEGER DEFAULT 0;
